name: build

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y gcc make python3-dev libncurses5-dev libncursesw5-dev 
      - name: Install python deps
        run: sudo pip install cython
      - name: Build
        run: make all
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unhex-build
          path: |
            bin/unhex
            python/*.so
